name: easy_dash_logger
description: "A versatile logging package for Dart and Flutter applications."
version: 1.0.0
homepage: https://github.com/mreslamgeek/easy_dash_logger
repository: https://github.com/mreslamgeek/easy_dash_logger

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.2

flutter:
  uses-material-design: true
